# .goreleaser.yml
version: 2
project_name: doplan

before:
  hooks:
    - go mod download

builds:
  - env:
      - CGO_ENABLED=0
    main: ./cmd/doplan
    binary: doplan
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    files:
      - README.md
      - LICENSE

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
  use: git
  groups:
    - title: 'Breaking Changes'
      regexp: '^.*(breaking|BREAKING).*'
      order: 0
    - title: 'Features'
      regexp: '^.*(feat|feature).*'
      order: 1
    - title: 'Bug Fixes'
      regexp: '^.*(fix|bug).*'
      order: 2
    - title: 'Other Changes'
      order: 999

# Homebrew configuration - disabled until tap repository is set up
# Will be enabled once homebrew-doplan repository exists
# brews:
#   - name: doplan
#     homepage: https://github.com/DoPlan-dev/CLI
#     description: Project workflow automation tool
#     license: MIT
#     tap:
#       owner: DoPlan-dev
#       name: homebrew-doplan
#     commit_author:
#       name: goreleaserbot
#       email: noreply@doplan.dev
#     folder: Formula
#     test: |
#       system "#{bin}/doplan --version"
#     install: |
#       bin.install "doplan"

nfpms:
  - package_name: doplan
    vendor: DoPlan
    homepage: https://github.com/DoPlan-dev/CLI
    maintainer: DoPlan Team <support@doplan.dev>
    description: Project workflow automation tool
    license: MIT
    formats:
      - deb
      - rpm
    bindir: /usr/bin

# Docker builds disabled for initial release - can be enabled later
# dockers:
#   - goos: linux
#     goarch: amd64
#     image_templates:
#       - "ghcr.io/doplan-dev/doplan:{{ .Tag }}"
#       - "ghcr.io/doplan-dev/doplan:latest"
#     dockerfile: Dockerfile
#     build_flag_templates:
#       - "--pull"
#       - "--label=org.opencontainers.image.created={{.Date}}"
#       - "--label=org.opencontainers.image.title={{.ProjectName}}"
#       - "--label=org.opencontainers.image.revision={{.FullCommit}}"
#       - "--label=org.opencontainers.image.version={{.Version}}"

release:
  github:
    owner: DoPlan-dev
    name: CLI
  mode: replace
  header: |
    ## Release Notes

    **DoPlan CLI v0.1.1-alpha - Initial Release**

    This is the first alpha release of DoPlan CLI, a comprehensive project workflow automation tool that transforms app ideas into structured development projects.

    ### Key Features
    - Project workflow automation with IDE integration
    - GitHub integration for automatic branching and PR management
    - Real-time progress tracking with visual dashboards
    - Document generation (PRD, project structure, API contracts)
    - Interactive TUI dashboard
    - Statistics and analytics with historical tracking
    - Checkpoint system for project snapshots

    ### Installation
    - Download binaries for Linux, macOS, and Windows (amd64 and arm64)
    - Install via npm: `npm install -g doplan-cli`
    - Homebrew support coming soon

    ### Documentation
    See [README.md](https://github.com/DoPlan-dev/CLI/blob/master/README.md) for full documentation.
