# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Doplan < Formula
  desc "Project workflow automation tool"
  homepage "https://github.com/DoPlan-dev/CLI"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/DoPlan-dev/CLI/releases/download/v1.0.0/doplan_1.0.0_darwin_amd64.tar.gz"
      sha256 "47e6837ed04e6cf1f1389c12313075b3eb809b025ab14b186423dfa78c8a4bb7"

      def install
        bin.install "doplan"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/DoPlan-dev/CLI/releases/download/v1.0.0/doplan_1.0.0_darwin_arm64.tar.gz"
      sha256 "fa3ebd2e19d51007d835a2ec84120209095333e5d56774a194508b7b53b7eef2"

      def install
        bin.install "doplan"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/DoPlan-dev/CLI/releases/download/v1.0.0/doplan_1.0.0_linux_amd64.tar.gz"
      sha256 "a5bb2bc860658578abb95fcba14696a2e57cd06bcc47a27297e1dc99c983af7c"
      def install
        bin.install "doplan"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/DoPlan-dev/CLI/releases/download/v1.0.0/doplan_1.0.0_linux_arm64.tar.gz"
      sha256 "84a593faaec7f9eaa6f9e5c0e93234b2beca7bdaf81e78a46ad73b766c024902"
      def install
        bin.install "doplan"
      end
    end
  end

  test do
    system "#{bin}/doplan --version"
  end
end
