package cli

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra"

	"github.com/DoPlan-dev/CLI/internal/tui"
	"github.com/DoPlan-dev/CLI/internal/version"
)

const (
	// AppName is the name of the application
	AppName = "doplan"
)

// Version returns the version of the application
func Version() string {
	return version.GetVersion()
}

var (
	// rootCmd represents the base command when called without any subcommands
	rootCmd = &cobra.Command{
		Use:   AppName,
		Short: "DoPlan CLI - Zero-install project generator with AI agency",
		Long: `DoPlan CLI is a zero-install, pure-Go command-line tool that instantly 
generates professional project structures with a complete hierarchical AI agency system.

Users can bootstrap production-ready projects in seconds with full automation, 
intelligent agents, and comprehensive rules libraries.

Examples:
  doplan              # Run interactive wizard to create a new project
  doplan --version    # Show version information
  doplan --help       # Show help information`,
		Version: Version(),
		// Default action: run the wizard
		Run: func(cmd *cobra.Command, args []string) {
			// Run the TUI wizard
			if err := runWizard(); err != nil {
				fmt.Fprintf(os.Stderr, "Error: %v\n", err)
				os.Exit(1)
			}
		},
	}
)

// Execute adds all child commands to the root command and sets flags appropriately.
// This is called by main.main(). It only needs to happen once to the rootCmd.
func Execute() {
	if err := rootCmd.Execute(); err != nil {
		fmt.Fprintf(os.Stderr, "Error: %v\n", err)
		os.Exit(1)
	}
}

// init initializes the root command with flags and configuration
func init() {
	// Add version flag
	rootCmd.Flags().BoolP("version", "v", false, "Print version information and exit")

	// Override version template to show custom version format
	rootCmd.SetVersionTemplate(fmt.Sprintf("%s version {{.Version}}\n", AppName))
}

// GetRootCmd returns the root command (useful for testing)
func GetRootCmd() *cobra.Command {
	return rootCmd
}

// runWizard runs the TUI wizard and handles the returned project data
func runWizard() error {
	request, err := tui.Run()
	if err != nil {
		return err
	}

	// If user quit without completing, exit gracefully
	if request == nil {
		fmt.Println("Wizard cancelled. No project created.")
		return nil
	}

	// Generation is now handled inside the wizard, so if we get here,
	// the project was successfully created
	fmt.Printf("\n✨ Project '%s' created successfully!\n", request.ProjectName)
	if len(request.IDEs) <= 1 {
		targetIDE := request.IDE
		if len(request.IDEs) == 1 {
			targetIDE = request.IDEs[0]
		}
		fmt.Printf("Open with: %s ./%s\n", getIDECommand(targetIDE), request.ProjectName)
	} else {
		fmt.Printf("Generated IDE configs for: %s\n", strings.Join(request.IDEs, ", "))
		for _, ide := range request.IDEs {
			fmt.Printf("- %s: %s ./%s\n", ide, getIDECommand(ide), request.ProjectName)
		}
	}
	fmt.Printf("Then type /tell to begin\n")

	projectPath := filepath.Join(".", request.ProjectName)
	if err := applyAccessPatch(projectPath); err != nil {
		fmt.Printf("⚠️  Could not auto-apply the access patch: %v\n", err)
		fmt.Printf("   Run manually from your project folder:\n")
		fmt.Printf("   npx --yes @doplan-dev/cli goplan access all\n")
	} else {
		fmt.Printf("✅ Access patch applied (.do/ + docs are writable). Need it again later?\n")
		fmt.Printf("   npx --yes @doplan-dev/cli goplan access all\n")
	}

	return nil
}

// getIDECommand returns the command to open a project in the selected IDE
func getIDECommand(ide string) string {
	switch ide {
	case "Cursor":
		return "cursor"
	case "Claude Code":
		return "claude"
	case "Antigravity":
		return "antigravity"
	case "Windsurf":
		return "windsurf"
	case "Cline":
		return "cline"
	case "OpenCode":
		return "opencode"
	default:
		return "code"
	}
}

const (
	defaultUserProfileJSON = `{
  "user_name": "",
  "user_experience_level": "",
  "development_support_mode": "guided",
  "first_hello_completed": false
}
`
	defaultQuickReference  = "# Quick Reference\n\nUse this file as your personal DoPlan cheat sheet.\n"
	defaultSharedQuickRef  = "# Quick Reference (Shared)\n\nThis mirrors .do/system/QUICK_REFERENCE.md.\n"
	defaultAgentHierarchy  = "# Agent Hierarchy\n\n(Generated by /hello)\n"
	defaultCommandExamples = "# Command Examples\n\n(Generated by /hello)\n"
	defaultTutorialNotes   = "# Tutorial Notes\n\n(Generated by /hello)\n"
	defaultOverviewReadme  = "# Project Overview\n\nRun `/write docs` to regenerate this file with the latest context. Until then, use it as a landing page for new collaborators.\n"
	defaultChangelog       = "# Changelog\n\nUse `/report` or `/finished` to keep this history up to date.\n"
	defaultTasksMarkdown   = "# Project Tasks\n\n- [ ] Example task\n"
)

func applyAccessPatch(projectPath string) error {
	if err := ensureDir(filepath.Join(projectPath, ".do", "system", "history")); err != nil {
		return err
	}
	if err := ensureFile(filepath.Join(projectPath, ".do", "system", "user_profile.json"), defaultUserProfileJSON); err != nil {
		return err
	}
	if err := ensureFile(filepath.Join(projectPath, ".do", "system", "QUICK_REFERENCE.md"), defaultQuickReference); err != nil {
		return err
	}
	if err := ensureDir(filepath.Join(projectPath, ".do", "plan", "history")); err != nil {
		return err
	}
	if err := ensureFile(filepath.Join(projectPath, ".do", "plan", "TASKS.md"), defaultTasksMarkdown); err != nil {
		return err
	}
	if err := ensureDir(filepath.Join(projectPath, "docs")); err != nil {
		return err
	}

	overviewDir := filepath.Join(projectPath, "docs", "overview")
	referencesDir := filepath.Join(projectPath, "docs", "references")
	tutorialsDir := filepath.Join(projectPath, "docs", "tutorials")
	historyDir := filepath.Join(projectPath, "docs", "history")

	if err := ensureDir(overviewDir); err != nil {
		return err
	}
	if err := ensureDir(referencesDir); err != nil {
		return err
	}
	if err := ensureDir(tutorialsDir); err != nil {
		return err
	}
	if err := ensureDir(historyDir); err != nil {
		return err
	}

	if err := ensureFile(filepath.Join(overviewDir, "README.md"), defaultOverviewReadme); err != nil {
		return err
	}
	if err := ensureFile(filepath.Join(overviewDir, "AGENT_HIERARCHY.md"), defaultAgentHierarchy); err != nil {
		return err
	}
	if err := ensureFile(filepath.Join(referencesDir, "QUICK_REFERENCE.md"), defaultSharedQuickRef); err != nil {
		return err
	}
	if err := ensureFile(filepath.Join(referencesDir, "COMMAND_EXAMPLES.md"), defaultCommandExamples); err != nil {
		return err
	}
	if err := ensureFile(filepath.Join(tutorialsDir, "TUTORIAL_NOTES.md"), defaultTutorialNotes); err != nil {
		return err
	}
	if err := ensureFile(filepath.Join(historyDir, "CHANGELOG.md"), defaultChangelog); err != nil {
		return err
	}

	return nil
}

func ensureDir(path string) error {
	if err := os.MkdirAll(path, 0o755); err != nil {
		return err
	}
	return os.Chmod(path, 0o755)
}

func ensureFile(path, defaultContent string) error {
	if err := ensureDir(filepath.Dir(path)); err != nil {
		return err
	}

	if info, err := os.Stat(path); err == nil {
		if info.Size() > 0 {
			return os.Chmod(path, 0o644)
		}
	}

	return os.WriteFile(path, []byte(defaultContent), 0o644)
}
