package generators

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"

	"github.com/DoPlan-dev/CLI/pkg/models"
)

// ContractsGenerator generates API contracts and data models
type ContractsGenerator struct {
	projectRoot string
	state       *models.State
}

// NewContractsGenerator creates a new contracts generator
func NewContractsGenerator(projectRoot string, state *models.State) *ContractsGenerator {
	return &ContractsGenerator{
		projectRoot: projectRoot,
		state:       state,
	}
}

// Generate creates API specification and data model documentation
func (g *ContractsGenerator) Generate() error {
	contractsDir := filepath.Join(g.projectRoot, "doplan", "contracts")

	if err := os.MkdirAll(contractsDir, 0755); err != nil {
		return err
	}

	// Generate API specification
	if err := g.generateAPISpec(contractsDir); err != nil {
		return err
	}

	// Generate data model documentation
	if err := g.generateDataModel(contractsDir); err != nil {
		return err
	}

	return nil
}

func (g *ContractsGenerator) generateAPISpec(contractsDir string) error {
	// OpenAPI 3.0 specification
	spec := map[string]interface{}{
		"openapi": "3.0.0",
		"info": map[string]interface{}{
			"title":       g.getProjectName(),
			"version":     "1.0.0",
			"description": "API specification for " + g.getProjectName(),
		},
		"servers": []map[string]interface{}{
			{
				"url":         "https://api.example.com/v1",
				"description": "Production server",
			},
		},
		"paths": map[string]interface{}{},
		"components": map[string]interface{}{
			"schemas": map[string]interface{}{},
		},
	}

	// Add endpoints from features
	if g.state != nil {
		for _, feature := range g.state.Features {
			if feature.TechnicalSpecs != "" {
				// Extract API endpoints from technical specs if available
				// This is a placeholder - in real implementation, parse technical specs
			}
		}
	}

	data, err := json.MarshalIndent(spec, "", "  ")
	if err != nil {
		return err
	}

	path := filepath.Join(contractsDir, "api-spec.json")
	return os.WriteFile(path, data, 0644)
}

func (g *ContractsGenerator) generateDataModel(contractsDir string) error {
	content := `# Data Model Documentation

## Overview

This document describes the data models used in the application.

## Models

`

	if g.state != nil && len(g.state.Features) > 0 {
		for _, feature := range g.state.Features {
			content += fmt.Sprintf("### %s\n\n", feature.Name)
			content += fmt.Sprintf("%s\n\n", feature.Description)
			content += "**Fields:**\n"
			content += "- To be defined\n\n"
		}
	} else {
		content += "No data models defined yet. Use /Generate to create data models.\n\n"
	}

	content += `## Relationships

To be defined.

## Validation Rules

To be defined.

---

*Generated by DoPlan - Project Workflow Manager*
`

	path := filepath.Join(contractsDir, "data-model.md")
	if err := os.WriteFile(path, []byte(content), 0644); err != nil {
		return err
	}
	return nil
}

func (g *ContractsGenerator) getProjectName() string {
	if g.state != nil && g.state.Idea != nil && g.state.Idea.Name != "" {
		return g.state.Idea.Name
	}
	return "Untitled Project"
}
