# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Doplan < Formula
  desc "Project workflow automation tool that transforms app ideas into structured development projects"
  homepage "https://github.com/DoPlan-dev/CLI"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/DoPlan-dev/CLI/releases/download/v1.0.0/doplan_1.0.0_darwin_amd64.tar.gz"
      sha256 "REPLACE_WITH_ACTUAL_SHA256_AFTER_FIRST_RELEASE"

      def install
        bin.install "doplan"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/DoPlan-dev/CLI/releases/download/v1.0.0/doplan_1.0.0_darwin_arm64.tar.gz"
      sha256 "REPLACE_WITH_ACTUAL_SHA256_AFTER_FIRST_RELEASE"

      def install
        bin.install "doplan"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/DoPlan-dev/CLI/releases/download/v1.0.0/doplan_1.0.0_linux_amd64.tar.gz"
      sha256 "REPLACE_WITH_ACTUAL_SHA256_AFTER_FIRST_RELEASE"

      def install
        bin.install "doplan"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/DoPlan-dev/CLI/releases/download/v1.0.0/doplan_1.0.0_linux_arm64.tar.gz"
      sha256 "REPLACE_WITH_ACTUAL_SHA256_AFTER_FIRST_RELEASE"

      def install
        bin.install "doplan"
      end
    end
  end

  test do
    system "#{bin}/doplan --version"
  end
end

