#!/bin/bash
# scripts/setup-homebrew-tap.sh
# Helper script to set up Homebrew tap repository

set -e

echo "🚀 Setting up Homebrew Tap Repository"
echo ""
echo "This script will help you set up the Homebrew tap repository for DoPlan CLI."
echo ""
echo "Prerequisites:"
echo "  - GitHub account with access to DoPlan-dev organization"
echo "  - GitHub CLI (gh) installed and authenticated"
echo "  - Git installed"
echo ""
read -p "Continue? (y/n) " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    exit 1
fi

# Check if gh is installed
if ! command -v gh &> /dev/null; then
    echo "❌ GitHub CLI (gh) is not installed."
    echo "   Install it from: https://cli.github.com/"
    exit 1
fi

# Check if authenticated
if ! gh auth status &> /dev/null; then
    echo "❌ GitHub CLI is not authenticated."
    echo "   Run: gh auth login"
    exit 1
fi

echo ""
echo "📋 Steps to set up Homebrew tap:"
echo ""
echo "1. Create repository: DoPlan-dev/homebrew-doplan"
echo "2. Initialize with Formula directory"
echo "3. Create initial formula template"
echo "4. Set up GitHub token for automation"
echo ""
read -p "Would you like to proceed with repository creation? (y/n) " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    echo "⏭️  Skipping repository creation."
    echo ""
    echo "📝 Manual setup instructions:"
    echo "   1. Go to: https://github.com/organizations/DoPlan-dev/repositories/new"
    echo "   2. Repository name: homebrew-doplan"
    echo "   3. Description: Homebrew tap for DoPlan CLI"
    echo "   4. Visibility: Public"
    echo "   5. Initialize with README: Yes"
    echo "   6. Create repository"
    echo ""
    echo "   Then follow the instructions in: docs/development/HOMEBREW_SETUP.md"
    exit 0
fi

# Create repository
echo ""
echo "📦 Creating repository: DoPlan-dev/homebrew-doplan"
if gh repo create DoPlan-dev/homebrew-doplan --public --description "Homebrew tap for DoPlan CLI" --clone; then
    echo "✅ Repository created successfully!"
else
    echo "❌ Failed to create repository. It may already exist."
    echo "   Check if it exists at: https://github.com/DoPlan-dev/homebrew-doplan"
    exit 1
fi

# Clone repository
echo ""
echo "📥 Cloning repository..."
cd homebrew-doplan

# Create Formula directory
echo "📁 Creating Formula directory..."
mkdir -p Formula

# Create initial formula template
echo "📝 Creating initial formula template..."
cat > Formula/doplan.rb << 'EOF'
# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Doplan < Formula
  desc "Project workflow automation tool that transforms app ideas into structured development projects"
  homepage "https://github.com/DoPlan-dev/CLI"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/DoPlan-dev/CLI/releases/download/v1.0.0/doplan_1.0.0_darwin_amd64.tar.gz"
      sha256 "REPLACE_WITH_ACTUAL_SHA256"

      def install
        bin.install "doplan"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/DoPlan-dev/CLI/releases/download/v1.0.0/doplan_1.0.0_darwin_arm64.tar.gz"
      sha256 "REPLACE_WITH_ACTUAL_SHA256"

      def install
        bin.install "doplan"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/DoPlan-dev/CLI/releases/download/v1.0.0/doplan_1.0.0_linux_amd64.tar.gz"
      sha256 "REPLACE_WITH_ACTUAL_SHA256"

      def install
        bin.install "doplan"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/DoPlan-dev/CLI/releases/download/v1.0.0/doplan_1.0.0_linux_arm64.tar.gz"
      sha256 "REPLACE_WITH_ACTUAL_SHA256"

      def install
        bin.install "doplan"
      end
    end
  end

  test do
    system "#{bin}/doplan --version"
  end
end
EOF

# Create README
echo "📝 Creating README..."
cat > README.md << 'EOF'
# homebrew-doplan

Homebrew tap for DoPlan CLI.

## Installation

```bash
brew install DoPlan-dev/doplan/doplan
```

## Documentation

See [DoPlan CLI](https://github.com/DoPlan-dev/CLI) for documentation.
EOF

# Commit and push
echo "📤 Committing and pushing..."
git add .
git commit -m "Initial commit: Add doplan formula" || true
git push origin main || git push origin master || true

# Go back to original directory
cd ..

echo ""
echo "✅ Homebrew tap repository set up successfully!"
echo ""
echo "📋 Next steps:"
echo "   1. Create GitHub Personal Access Token with 'repo' scope"
echo "   2. Add token to GitHub Secrets:"
echo "      - Go to: https://github.com/DoPlan-dev/CLI/settings/secrets/actions"
echo "      - Add secret: HOMEBREW_TAP_TOKEN"
echo "      - Value: Your GitHub token"
echo ""
echo "   3. Test the formula:"
echo "      brew tap DoPlan-dev/doplan"
echo "      brew install doplan"
echo ""
echo "   4. On next release, GoReleaser will automatically:"
echo "      - Generate formula with correct version and SHA256"
echo "      - Create PR to homebrew-doplan repository"
echo ""
echo "📖 For more information, see: docs/development/HOMEBREW_SETUP.md"

