package generator

import (
	"fmt"
	"path/filepath"
	"strings"

	"github.com/DoPlan-dev/CLI/internal/utils"
	"github.com/DoPlan-dev/CLI/pkg/models"
)

// DocsGenerator generates documentation files
type DocsGenerator struct{}

// Name returns the name of the generator
func (g *DocsGenerator) Name() string {
	return "Documentation"
}

// Generate creates documentation files
func (g *DocsGenerator) Generate(request *models.ProjectRequest, projectPath string) error {
	// Generate README.md
	if err := generateREADME(projectPath, request); err != nil {
		return fmt.Errorf("failed to generate README.md: %w", err)
	}

	// Generate STANDUP.md
	if err := generateSTANDUP(projectPath, request); err != nil {
		return fmt.Errorf("failed to generate STANDUP.md: %w", err)
	}

	// Generate CHANGELOG.md
	if err := generateCHANGELOG(projectPath, request); err != nil {
		return fmt.Errorf("failed to generate CHANGELOG.md: %w", err)
	}

	// Generate rules README
	if err := generateRulesREADME(projectPath, request); err != nil {
		return fmt.Errorf("failed to generate rules README: %w", err)
	}

	// Scaffold Docs/ hierarchy
	if err := generateDocsHierarchy(projectPath); err != nil {
		return fmt.Errorf("failed to scaffold Docs hierarchy: %w", err)
	}

	return nil
}

// generateREADME generates README.md
func generateREADME(projectPath string, request *models.ProjectRequest) error {
	// Get IDE command
	ideCommand := getIDECommand(request.IDE)

	content := `# ` + request.ProjectName + `

Generated by [DoPlan](https://github.com/DoPlan-dev/CLI) - Zero-install AI Project Director

## Quick Start

1. Open this project in your IDE (` + request.IDE + `)
2. Type /tell to capture your project idea
3. Follow the commands below to build your project

## Commands

### Core Commands

- **/tell** → Capture your project idea
- **/improve** → Team brainstorm session
- **/team** → Show active agents and hierarchy
- **/write** → Generate PRD + ARCHITECTURE + DESIGN_SYSTEM
- **/change** → Edit any document (e.g., /change prd Add dark mode)
- **/good** → Approve & lock the plan
- **/tasks** → Generate TASKS.md from approved plan
- **/load** → Inject context into AI agents
- **/build** → Start coding next task (or /build 3 for specific task)
- **/progress** → Show current progress
- **/finished** → Mark current task done

### Squad-Specific Commands

- **/ship** → Release management
- **/safe** → Security audit
- **/cheap** → Cost optimization

## Project Structure

` + request.ProjectName + `/
  .cursor/
    agents/           - 18 full persona prompts
    commands/         - Command definitions
    rules/            - Rules library (15 categories, 1000+ rules)
      library/       - Embedded rules for all tech stacks
  .plan/
    00_System/       - IDEA.md, PRD.md, ARCHITECTURE.md, DESIGN_SYSTEM.md
    TASKS.md         - Implementation tasks
    active_state.json - Current project state
  src/                 - Your source code
  STANDUP.md           - Daily standup notes
  README.md            - This file

## Workflow

1. **Idea** → Type /tell to capture your idea
2. **Brainstorm** → Type /improve to brainstorm with the team
3. **Plan** → Type /write to generate all planning documents
4. **Approve** → Type /good to approve and lock the plan
5. **Tasks** → Type /tasks to generate implementation tasks
6. **Code** → Type /build to start coding
7. **Progress** → Type /progress to see how you're doing

## Agents

This project uses a hierarchical AI agency with 18 specialized agents:

- **Project Orchestrator** - Coordinates all agents and project execution
- **Product Manager** - Manages product requirements and roadmap
- **Engineering Lead** - Coordinates technical implementation
- **System Architect** - Designs system architecture
- **Frontend Lead** - Manages frontend development
- **Backend Lead** - Manages backend development
- **DevOps Engineer** - Handles infrastructure and deployment
- **Security Lead** - Ensures security best practices
- **Performance Engineer** - Optimizes performance
- **Design & UX Manager** - Manages design system
- **UI/UX Designer** - Creates user interfaces
- **QA & Reliability Manager** - Manages quality assurance
- **QA Engineer** - Tests and validates code
- **Release & Growth Manager** - Manages releases and growth
- **Release Captain** - Coordinates releases
- **Growth Coach** - Drives user growth
- **Documentation Lead** - Manages documentation
- **Documentation Writer** - Writes documentation

See .cursor/agents/ for full agent definitions.

## Getting Started

` + "```bash" + `
# Install dependencies
npm install

# Run development server
npm run dev
` + "```" + `

Open ` + ideCommand + ` ./` + request.ProjectName + ` to start working with your AI agency.

## Next Steps

1. Type **/tell** to capture your project idea
2. Type **/improve** to brainstorm with the team
3. Type **/write** to generate planning documents
4. Type **/good** to approve the plan
5. Type **/tasks** to generate implementation tasks
6. Type **/build** to start coding

---

*Generated by DoPlan CLI*
`
	path := filepath.Join(projectPath, "README.md")
	return utils.WriteFile(path, []byte(content))
}

// getIDECommand returns the command to open the project in the selected IDE
func getIDECommand(ide string) string {
	switch strings.ToLower(ide) {
	case "cursor":
		return "cursor"
	case "claude code", "claudecode":
		return "claude"
	case "antigravity":
		return "antigravity"
	case "windsurf":
		return "windsurf"
	case "cline":
		return "cline"
	case "opencode":
		return "opencode"
	default:
		return "code"
	}
}

// generateSTANDUP generates STANDUP.md template
func generateSTANDUP(projectPath string, request *models.ProjectRequest) error {
	content := `# Daily Standup

## Date: [YYYY-MM-DD]

### Yesterday
- [ ] Task completed
- [ ] Task completed

### Today
- [ ] Task to work on
- [ ] Task to work on

### Blockers
- None

### Notes
- Add any relevant notes here

---

## Previous Standups

### [YYYY-MM-DD]
**Completed:**
- Task 1
- Task 2

**Today:**
- Task 3
- Task 4

**Blockers:**
- None

---

*Use this template for daily standups. Update the date and fill in your progress each day.*
`
	path := filepath.Join(projectPath, "STANDUP.md")
	return utils.WriteFile(path, []byte(content))
}

// generateCHANGELOG generates CHANGELOG.md template
func generateCHANGELOG(projectPath string, request *models.ProjectRequest) error {
	content := `# Changelog

All notable changes to this project will be documented in this file.

The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),
and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).

## [Unreleased]

### Added
- Initial project setup

### Changed
- 

### Deprecated
- 

### Removed
- 

### Fixed
- 

### Security
- 

---

## [0.1.0] - YYYY-MM-DD

### Added
- Initial release

---

## Version Format

- **MAJOR** version when you make incompatible API changes
- **MINOR** version when you add functionality in a backwards compatible manner
- **PATCH** version when you make backwards compatible bug fixes

## Change Categories

- **Added** for new features
- **Changed** for changes in existing functionality
- **Deprecated** for soon-to-be removed features
- **Removed** for now removed features
- **Fixed** for any bug fixes
- **Security** for vulnerability fixes

*Generated by DoPlan CLI*
`
	path := filepath.Join(projectPath, "CHANGELOG.md")
	return utils.WriteFile(path, []byte(content))
}

// generateRulesREADME generates .cursor/rules/README.md
func generateRulesREADME(projectPath string, request *models.ProjectRequest) error {
	content := `# Project Rules

## Rules Library

This directory contains a comprehensive rules library organized by category. These rules are automatically loaded by your IDE's AI assistant to guide development practices.

## Categories

### 01-core-workflow/
Core development workflow rules including:
- GitHub workflow automation
- Branching strategies
- Commit conventions
- Code review practices

### 02-ai-agents/
AI agent interaction guidelines:
- Agent hierarchy and responsibilities
- Command definitions
- Agent activation patterns

### 03-languages/
Language-specific rules for:
- Go
- Python
- TypeScript
- JavaScript
- And more...

### 04-frameworks/
Framework-specific rules for:
- Next.js
- React
- Express
- And more...

### 05-ui-libraries/
UI library rules and best practices

### 06-cloud-infrastructure/
Cloud platform rules for:
- AWS
- GCP
- Azure
- And more...

### 07-databases/
Database rules for:
- PostgreSQL
- MongoDB
- And more...

### 08-testing/
Testing framework rules for:
- Jest
- Vitest
- Go testing
- And more...

### 09-devops-ci-cd/
DevOps and CI/CD rules:
- GitHub Actions
- GitLab CI
- Deployment strategies
- Infrastructure as Code

### 10-code-quality/
Code quality and linting rules:
- ESLint configurations
- Code style guidelines
- Best practices

### 11-documentation/
Documentation standards and practices

### 12-security/
Security best practices:
- Authentication
- Data encryption
- Security audits
- Vulnerability management

### 13-development-practices/
General development practices and patterns

### 14-mcp-tools/
MCP (Model Context Protocol) tool integration rules

### 15-project-specific/
Project-specific rules and conventions

## Usage

These rules are automatically loaded by your IDE's AI assistant. The rules are organized hierarchically and cover:

- Coding standards and best practices
- Framework-specific patterns
- Security guidelines
- Testing strategies
- Documentation standards
- And much more!

## Referencing Rules

To reference a specific rule in your commands or agent prompts, use:

` + "```" + `
@library/03-languages/go/go.md
@library/04-frameworks/frontend/nextjs.md
@library/09-devops-ci-cd/github-actions.md
` + "```" + `

## Custom Rules

Add your project-specific rules in this directory or create new markdown files that reference the library rules.

## Contributing

When adding new rules:
1. Place them in the appropriate category directory
2. Follow the existing naming conventions
3. Include clear examples and explanations
4. Update this README if adding a new category

---

*Generated by DoPlan CLI*
`
	rulesDir := filepath.Join(projectPath, ".cursor", "rules")
	if err := utils.CreateDirectory(rulesDir); err != nil {
		return fmt.Errorf("failed to create .cursor/rules directory: %w", err)
	}
	path := filepath.Join(rulesDir, "README.md")
	return utils.WriteFile(path, []byte(content))
}

func generateDocsHierarchy(projectPath string) error {
	docsRoot := filepath.Join(projectPath, "Docs")
	if err := utils.CreateDirectory(docsRoot); err != nil {
		return err
	}

	categories := []struct {
		name string
		desc string
	}{
		{"foundation", "Global references shared across the product"},
		{"features", "Feature-scoped specs, tasks, and histories"},
		{"release", "Launch-readiness docs, retros, checklists"},
		{"history", "Prompt transcripts, changelog excerpts, PR logs"},
	}

	for _, cat := range categories {
		dir := filepath.Join(docsRoot, cat.name)
		if err := utils.CreateDirectory(dir); err != nil {
			return err
		}
		gitkeep := filepath.Join(dir, ".gitkeep")
		if err := utils.WriteFile(gitkeep, []byte("")); err != nil {
			return err
		}
	}

	readmeContent := "# Docs Directory\n\n" +
		"DoPlan keeps every long-form artifact inside `Docs/` so the repository root stays clean. Use these canonical subfolders:\n\n" +
		"| Directory | Purpose |\n" +
		"| --- | --- |\n" +
		"| `Docs/foundation/` | Global system references, roadmaps, and guides |\n" +
		"| `Docs/features/` | Feature-specific specs, plans, and task checklists |\n" +
		"| `Docs/release/` | Launch readiness, release notes, retrospectives |\n" +
		"| `Docs/history/` | Prompt logs, changelog excerpts, Git/PR summaries |\n\n" +
		"## Rules\n\n" +
		"1. **All docs live under `Docs/`.** Root-level additions are limited to `README.md` and `CHANGELOG.md`.\n" +
		"2. **One document = one place.** Link references instead of duplicating content.\n" +
		"3. **Feature folders mirror task IDs** (e.g., `Docs/features/01_Auth_Feature/`).\n" +
		"4. **History stays in `Docs/history/`.** Capture prompts, retros, and audit trails there.\n\n" +
		"Need another category? Create it under `Docs/` and update this README so future scans stay consistent.\n"

	readmePath := filepath.Join(docsRoot, "README.md")
	return utils.WriteFile(readmePath, []byte(readmeContent))
}

// GenerateDocumentation is a convenience function that creates a DocsGenerator and generates documentation
func GenerateDocumentation(request *models.ProjectRequest, projectPath string) error {
	generator := &DocsGenerator{}
	return generator.Generate(request, projectPath)
}
