package generator

import (
	"encoding/json"
	"fmt"
	"path/filepath"

	"github.com/doplan/cli/internal/utils"
	"github.com/doplan/cli/pkg/models"
)

// PlanGenerator generates the .plan/ directory structure
type PlanGenerator struct{}

// Name returns the name of the generator
func (g *PlanGenerator) Name() string {
	return ".plan Structure"
}

// Generate creates the .plan/ directory structure with all planning documents
func (g *PlanGenerator) Generate(request *models.ProjectRequest, projectPath string) error {
	planDir := filepath.Join(projectPath, ".plan")
	systemDir := filepath.Join(planDir, "00_System")

	// Create .plan/00_System/ directory
	if err := utils.CreateDirectory(systemDir); err != nil {
		return fmt.Errorf("failed to create .plan/00_System directory: %w", err)
	}

	// Generate IDEA.md
	if err := generateIDEA(systemDir, request); err != nil {
		return fmt.Errorf("failed to generate IDEA.md: %w", err)
	}

	// Generate BRAINSTORM.md
	if err := generateBRAINSTORM(systemDir, request); err != nil {
		return fmt.Errorf("failed to generate BRAINSTORM.md: %w", err)
	}

	// Generate PRD.md
	if err := generatePRD(systemDir, request); err != nil {
		return fmt.Errorf("failed to generate PRD.md: %w", err)
	}

	// Generate ARCHITECTURE.md
	if err := generateARCHITECTURE(systemDir, request); err != nil {
		return fmt.Errorf("failed to generate ARCHITECTURE.md: %w", err)
	}

	// Generate DESIGN_SYSTEM.md
	if err := generateDESIGNSYSTEM(systemDir, request); err != nil {
		return fmt.Errorf("failed to generate DESIGN_SYSTEM.md: %w", err)
	}

	// Generate TASKS.md
	if err := generateTASKS(planDir, request); err != nil {
		return fmt.Errorf("failed to generate TASKS.md: %w", err)
	}

	// Generate active_state.json
	if err := generateActiveState(planDir, request); err != nil {
		return fmt.Errorf("failed to generate active_state.json: %w", err)
	}

	return nil
}

// generateIDEA generates IDEA.md template
func generateIDEA(systemDir string, request *models.ProjectRequest) error {
	content := `# Project Idea

## Overview
Describe your project idea here.

## Goals
- Goal 1
- Goal 2
- Goal 3

## Target Users
- User persona 1
- User persona 2

## Key Features
- Feature 1
- Feature 2
- Feature 3

## Success Metrics
- Metric 1
- Metric 2

---
*Generated by DoPlan CLI*
`
	path := filepath.Join(systemDir, "IDEA.md")
	return utils.WriteFile(path, []byte(content))
}

// generateBRAINSTORM generates BRAINSTORM.md template
func generateBRAINSTORM(systemDir string, request *models.ProjectRequest) error {
	content := `# Brainstorm Session

## Questions & Insights

### Product Manager
**Questions**:
- What problem are we solving?
- Who is our target audience?

**Insights**:
- Insight 1
- Insight 2

### Engineering Lead
**Questions**:
- What are the technical requirements?
- What are the constraints?

**Insights**:
- Insight 1
- Insight 2

### Design Manager
**Questions**:
- What is the user experience we want to create?
- What are the design constraints?

**Insights**:
- Insight 1
- Insight 2

---
*Generated by DoPlan CLI*
`
	path := filepath.Join(systemDir, "BRAINSTORM.md")
	return utils.WriteFile(path, []byte(content))
}

// generatePRD generates PRD.md template
func generatePRD(systemDir string, request *models.ProjectRequest) error {
	content := `# Product Requirements Document

## Product Overview
**Product Name**: ` + request.ProjectName + `
**Version**: 1.0.0
**Status**: Draft

## User Personas
### Primary Persona
- **Name**: [Persona Name]
- **Role**: [Role]
- **Goals**: [Goals]
- **Pain Points**: [Pain Points]

## Features
### Feature 1
**Priority**: P0
**Description**: [Description]
**User Stories**:
- As a [user], I want [goal] so that [benefit]

**Acceptance Criteria**:
- [ ] Criterion 1
- [ ] Criterion 2

## Success Metrics
- Metric 1: [Target]
- Metric 2: [Target]

## Timeline
- Phase 1: [Dates]
- Phase 2: [Dates]

---
*Generated by DoPlan CLI*
`
	path := filepath.Join(systemDir, "PRD.md")
	return utils.WriteFile(path, []byte(content))
}

// generateARCHITECTURE generates ARCHITECTURE.md template
func generateARCHITECTURE(systemDir string, request *models.ProjectRequest) error {
	content := `# Technical Architecture

## System Overview
**Project**: ` + request.ProjectName + `
**Version**: 1.0.0
**Status**: Draft

## Technology Stack
### Frontend
- Framework: [Framework]
- UI Library: [Library]

### Backend
- Language: [Language]
- Framework: [Framework]

### Database
- Type: [Type]
- Database: [Database]

## System Design
### Architecture Pattern
[Pattern description]

### Components
1. Component 1
2. Component 2
3. Component 3

## API Design
### Endpoints
- GET /api/...
- POST /api/...

## Data Models
### Model 1
` + "```" + `
{
  "field1": "type",
  "field2": "type"
}
` + "```" + `

## Infrastructure
### Deployment
- Platform: [Platform]
- Environment: [Environment]

---
*Generated by DoPlan CLI*
`
	path := filepath.Join(systemDir, "ARCHITECTURE.md")
	return utils.WriteFile(path, []byte(content))
}

// generateDESIGNSYSTEM generates DESIGN_SYSTEM.md template
func generateDESIGNSYSTEM(systemDir string, request *models.ProjectRequest) error {
	content := `# Design System

## Design Principles
1. Principle 1
2. Principle 2
3. Principle 3

## Color Palette
### Primary Colors
- Primary: #000000
- Secondary: #FFFFFF

### Semantic Colors
- Success: #00FF00
- Error: #FF0000
- Warning: #FFFF00

## Typography
### Headings
- H1: [Font], [Size], [Weight]
- H2: [Font], [Size], [Weight]

### Body
- Body: [Font], [Size], [Weight]

## Components
### Button
- Primary Button
- Secondary Button

### Form Elements
- Input Field
- Select Dropdown

## Spacing
- Base Unit: 8px
- Scale: 8, 16, 24, 32, 40, 48

---
*Generated by DoPlan CLI*
`
	path := filepath.Join(systemDir, "DESIGN_SYSTEM.md")
	return utils.WriteFile(path, []byte(content))
}

// generateTASKS generates TASKS.md template
func generateTASKS(planDir string, request *models.ProjectRequest) error {
	content := `# Implementation Tasks

## Phase 1: Foundation
**Status**: ⏳ Pending

### Task 1.1
**Description**: [Description]
**Status**: ⏳ Pending
**Dependencies**: None
**Effort**: [Hours]

## Phase 2: Core Features
**Status**: ⏳ Pending

### Task 2.1
**Description**: [Description]
**Status**: ⏳ Pending
**Dependencies**: Phase 1
**Effort**: [Hours]

---
*Generated by DoPlan CLI*
*Use /tasks command to generate detailed tasks from approved plan*
`
	path := filepath.Join(planDir, "TASKS.md")
	return utils.WriteFile(path, []byte(content))
}

// generateActiveState generates active_state.json with initial state
func generateActiveState(planDir string, request *models.ProjectRequest) error {
	state := map[string]interface{}{
		"phase":       "idea",
		"active_task": nil,
		"completed":   []string{},
		"locked":      false,
	}

	jsonData, err := json.MarshalIndent(state, "", "  ")
	if err != nil {
		return fmt.Errorf("failed to marshal active_state.json: %w", err)
	}

	path := filepath.Join(planDir, "active_state.json")
	return utils.WriteFile(path, jsonData)
}

// GeneratePlan is a convenience function that creates a PlanGenerator and generates plan structure
func GeneratePlan(request *models.ProjectRequest, projectPath string) error {
	generator := &PlanGenerator{}
	return generator.Generate(request, projectPath)
}

